# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181209_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='blogger',
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
