# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180321_2015'),
        ('content', '0004_auto_20161124_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('keyedtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.KeyedType')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ResourceType')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.keyedtype',),
        ),
    ]
