# Generated by Django 2.2.3 on 2019-09-05 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_pagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyslot',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='copyslot',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copyslot',
            name='modifieddate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='copyslot',
            name='_body',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='copyslot',
            name='copy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='content.Copy'),
        ),
        migrations.AlterField(
            model_name='arrangementslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='copyslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dateslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='datetimeslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enumslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='instantslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='integerslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='menuslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pageslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='periodslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
