# Generated by Django 2.2.3 on 2019-09-05 17:55

from django.db import migrations

#-------------------------------------------------------------------------------
def merge_copy_and_copy_slot(apps, schema_editor):

    Copy = apps.get_model('content', 'Copy')
    CopySlot = apps.get_model('content', 'CopySlot')

    for slot in CopySlot.objects.all():
        slot.body = slot.copy.body
        slot.creationdate = slot.creationdate
        slot.save()

#-------------------------------------------------------------------------------
class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20190905_1754'),
    ]

    operations = [
        migrations.RunPython(
            merge_copy_and_copy_slot, migrations.RunPython.noop
        )
    ]
