# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20180809_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagevariant',
            name='documentation',
            field=models.CharField(blank=True, help_text='Document where this variant is used in the project.', max_length=255, null=True),
        ),
    ]
